# Generated by Django 5.1.1 on 2024-09-10 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propriete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_service', models.CharField(choices=[('LB', 'LIBRE'), ('IM', 'IMMOBILIER'), ('RS', 'RESTAURATION'), ('CM', 'COMMERCIAL'), ('ID', 'INDUSTRIEL'), ('SP', 'SERVICE_PUBLIC'), ('SS', 'SERVICE_SOCIAL'), ('VT', 'VERT'), ('ED', 'EDUCATION'), ('TS', 'TRANSPORT')], max_length=2)),
                ('disponible', models.BooleanField()),
                ('valeur_courrante', models.IntegerField()),
                ('valeur_achat', models.IntegerField()),
                ('position_x', models.IntegerField()),
                ('position_y', models.IntegerField()),
                ('longueur', models.IntegerField()),
                ('largeur', models.IntegerField()),
                ('condition_pourcentage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_utilisateur', models.CharField(choices=[('AD', 'ADMINISTRATEUR'), ('IV', 'INVESTISSEUR')], max_length=2)),
                ('nom', models.CharField(max_length=32)),
                ('prenom', models.CharField(max_length=32)),
                ('courriel_electronique', models.EmailField(max_length=254)),
                ('hash_mot_de_passe', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Habitant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('satisfaction', models.FloatField(default=0.0)),
                ('propriete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='immobilier.propriete')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_de_transaction', models.CharField(choices=[('VT', 'VENTE'), ('AC', 'ACHAT')], max_length=2)),
                ('prix', models.FloatField()),
                ('date', models.DateField()),
                ('propriete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='immobilier.propriete')),
                ('acheteur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_as_acheteur', to='immobilier.utilisateur')),
                ('vendeur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_as_vendeur', to='immobilier.utilisateur')),
            ],
        ),
        migrations.AddField(
            model_name='propriete',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='immobilier.utilisateur'),
        ),
    ]
