# Generated by Django 5.1.1 on 2024-09-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0002_alter_habitant_propriete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitant',
            name='est_employe',
            field=models.BooleanField(default=False),
        ),
    ]
