# Generated by Django 5.1.1 on 2024-09-11 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitant',
            name='propriete',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='immobilier.propriete'),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='proprietaire',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='immobilier.utilisateur'),
        ),
    ]
