# Generated by Django 5.1.1 on 2024-09-11 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0003_habitant_est_employe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitant',
            name='propriete',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='immobilier.propriete'),
        ),
    ]
