# Generated by Django 5.1.1 on 2024-09-11 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0005_remove_utilisateur_hash_mot_de_passe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 20, 54, 52, 825694, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$JPfiDegI8S9rYwHELsEf30$2Do3RoBJTZlezT2wVj5WZx9iUU9+ydjzpSdy5DbMElE=', max_length=128),
        ),
    ]
