# Generated by Django 5.1.1 on 2024-09-11 20:57

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0006_alter_utilisateur_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriete',
            name='proprietaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 20, 57, 52, 170952, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$W7tngrgBOhCICa10wTCB5E$ILsvUzwcv9P4wHuz310RlxA9AdXWdJ2RVP3duj1uTDc=', max_length=128),
        ),
    ]
