# Generated by Django 5.1.1 on 2024-09-11 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0007_alter_propriete_proprietaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 21, 1, 40, 653328, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$Z26LJCKXGyRC7NiIAEjEPS$NSOBqCH+k8uR3WLJNuw0MGEXTRPK+GfWUzW8BTVTNNY=', max_length=128),
        ),
    ]
