# Generated by Django 5.1.1 on 2024-09-11 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0008_alter_utilisateur_date_joined_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propriete',
            old_name='type_service',
            new_name='type_propriete',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 21, 43, 34, 635266, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$9LPDi2ttyrMEcGPGyeDg8u$r63KmGT+STwWbZPui/EwC2BsSYywAwhcdoQhMiWXekw=', max_length=128),
        ),
    ]
