# Generated by Django 5.1.1 on 2024-09-11 22:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0009_rename_type_service_propriete_type_propriete_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('point_x_depart', models.IntegerField()),
                ('point_y_depart', models.IntegerField()),
                ('longueur', models.IntegerField()),
                ('largeur', models.IntegerField()),
                ('taux_de_criminalite', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 22, 46, 51, 554815, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$qOJNbJHyrfVTv7necOQNeg$KlXqskgSQMccu4ImZx/87LbkbuqQKhyZyaY/gcFekPM=', max_length=128),
        ),
    ]
